apiVersion: v1
kind: Pod
metadata:
  name: workflow-demo-pod
  namespace: default
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: workflow-sa
  containers:
    - image: docker.io/adamkielar/workflow-identity-demo:v1.0.0
      name: workflow-demo-container
      envFrom:
      - secretRef:
          name: chatgpt-secrets
  nodeSelector:
    kubernetes.io/os: linux